# Generated by Django 4.1.5 on 2023-01-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.CharField(max_length=50, verbose_name='카드토큰')),
                ('oiling_type', models.CharField(choices=[('2', '고급휘발유'), ('1', '휘발유'), ('0', '경유')], max_length=10, verbose_name='유종')),
                ('oiling_price', models.CharField(choices=[('10', '가득'), ('9', '10만원'), ('8', '9만원'), ('7', '8만원'), ('6', '7만원'), ('5', '6만원'), ('4', '5만원'), ('3', '4만원'), ('2', '3만원'), ('1', '2만원'), ('0', '1만원')], max_length=10, verbose_name='금액')),
            ],
            options={
                'verbose_name': '카드정보',
                'verbose_name_plural': '카드정보',
                'db_table': 'CARDINFO_TB',
            },
        ),
    ]
