# Generated by Django 4.1.5 on 2023-01-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_info',
            name='oiling_receipt',
            field=models.CharField(choices=[('1', 'NO'), ('0', 'YES')], default=1, max_length=10, verbose_name='영수증발행여부'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card_info',
            name='point_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='포인트카드토큰'),
        ),
    ]
