# Generated by Django 4.1.5 on 2023-01-30 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_card_info_oiling_receipt_card_info_point_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card_info')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='아이디')),
            ],
            options={
                'verbose_name': '유저카드',
                'verbose_name_plural': '유저카드',
                'db_table': 'USERCARD_TB',
            },
        ),
    ]
