# Generated by Django 4.1.5 on 2023-01-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_user_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_info',
            name='card_nickname',
            field=models.CharField(default=1, max_length=10, verbose_name='카드닉네임'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card_info',
            name='point_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='포인트카드번호'),
        ),
    ]
