# Generated by Django 4.1.5 on 2023-01-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_info_card_nickname_alter_card_info_point_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_info',
            old_name='point_token',
            new_name='point_number',
        ),
    ]
