# Generated by Django 4.1.5 on 2023-01-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authsms_alter_user_hp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthSMS',
        ),
    ]
