# Generated by Django 4.1.5 on 2023-01-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_authsms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.CharField(max_length=6, null=True, verbose_name='인증번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='아이디'),
        ),
    ]
